#!/usr/bin/env node
/**
 * Setup wizard for the deepseek-web bridge.
 *
 * One script does the boring parts: checks Node, generates a bearer token,
 * writes a .env, and prints the exact next command for the path the user
 * picked (CLI-only or dsh). No config editing by hand.
 *
 * Run: node scripts/setup.mjs
 *
 * @module deepseek-web-bridge/scripts/setup
 */

import { randomBytes } from 'node:crypto'
import { existsSync, writeFileSync, readFileSync } from 'node:fs'

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')
const ENV_PATH = `${ROOT}/deepseek-web-mcp/.env`

function readLine() {
  return new Promise((resolve) => {
    process.stdin.resume()
    process.stdin.setEncoding('utf8')
    process.stdin.once('data', (data) => {
      process.stdin.pause()
      resolve(data.trim())
    })
  })
}

function checkNode() {
  const major = Number.parseInt(process.versions.node, 10)
  if (major < 20) {
    console.error(`✗ Node ${process.versions.node} found; this needs Node >= 20.`)
    console.error('  Install from https://nodejs.org/ and rerun.')
    process.exit(1)
  }
  console.log(`✓ Node ${process.versions.node}`)
}

function checkSubmodules() {
  const dirs = ['deepseek-web-mcp/src', 'dsh-deepseek-plugins/dsh-mcp-server', 'deepseek-pp-delegate/core']
  const missing = dirs.filter((d) => !existsSync(`${ROOT}/${d}`))
  if (missing.length > 0) {
    console.error('✗ Submodules are not initialized. Run:')
    console.error('    git submodule update --init --recursive')
    process.exit(1)
  }
  console.log('✓ Submodules present')
}

function generateToken() {
  return randomBytes(32).toString('hex')
}

function writeEnv(token) {
  const lines = [
    '# Generated by scripts/setup.mjs',
    `DWM_TOKEN=${token}`,
    'DWM_PORT=8765',
    'DWM_HOST=127.0.0.1',
    '# Add your browser extension id after loading the fork, e.g.',
    '# DWM_ALLOWED_ORIGINS=chrome-extension://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  ]
  writeFileSync(ENV_PATH, lines.join('\n'), 'utf8')
  console.log(`✓ Wrote ${ENV_PATH.replace(ROOT, '.')}`)
}

async function pickPath() {
  console.log('\nWhich path are you setting up?')
  console.log('  1) CLI only — use DeepSeek web as a subagent from Claude CLI / Codex CLI (no dsh)')
  console.log('  2) dsh — full DeepSeek Harness integration with subagent_deepseek_web')
  const answer = await readLine()
  return answer === '2' ? 'dsh' : 'cli'
}

function printNext(path, token) {
  const url = 'http://127.0.0.1:8765/mcp'
  console.log('\n────────────────────────────────────────────')
  console.log('Next steps')
  console.log('────────────────────────────────────────────')

  console.log('\n1. Start the MCP server (in one terminal):')
  console.log('   cd deepseek-web-mcp && node index.js')

  console.log('\n2. Build and load the browser delegate:')
  console.log('   cd deepseek-pp-delegate && npm install && npm run build:chrome')
  console.log('   Then load dist/chrome-mv3 in your browser at chrome://extensions')
  console.log('   Open chat.deepseek.com, sign in, open the DS++ sidebar,')
  console.log('   add an MCP server:')
  console.log(`     transport: streamable_http`)
  console.log(`     URL:       ${url}`)
  console.log(`     secret:    bearer, value: ${token.slice(0, 8)}... (full token in .env)`)
  console.log('   Then from the sidebar DevTools console (right-click sidebar → Inspect):')
  console.log('     chrome.runtime.sendMessage({ type: "START_DELEGATE" }, (r) => console.log(r))')

  if (path === 'cli') {
    console.log('\n3. Add the MCP server to your CLI:')
    console.log(`   claude mcp add --transport http deepseek-web ${url} \\`)
    console.log(`     --header "Authorization: Bearer <token>"   (full token in .env)`)
    console.log('\n4. Delegate from your CLI session:')
    console.log('   > 用 delegate_to_ds_web 列出当前目录的文件')
  } else {
    console.log('\n3. Install the dsh plugins (see dsh-deepseek-plugins/README.md for the preset row):')
    console.log('   dsh plugin --profile web add ./dsh-deepseek-plugins/dsh-mcp-server')
    console.log('   dsh plugin --profile web add ./dsh-deepseek-plugins/dsh-subagent-deepseek-web')
    console.log('\n4. Set the token + origin in ~/.dsh/profiles/web/cordis.patch.yml:')
    console.log('     token: <token>   (full token in deepseek-web-mcp/.env)')
    console.log('     allowedOrigins: [chrome-extension://<your-extension-id>]')
    console.log('     agentPreset: web-delegate')
    console.log('\n5. Start dsh, open a session on the web-delegate preset, then:')
    console.log('   > 用 subagent_deepseek_web 委派：列出当前目录')
  }

  console.log('\nTip: the token is in deepseek-web-mcp/.env — treat it like an API key.')
}

checkNode()
checkSubmodules()
const token = generateToken()
writeEnv(token)
const path = await pickPath()
printNext(path, token)
